pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                git(url: 'https://github.com/dev-hack95/devops_project_1', branch: 'main')
            }
        }
        
        stage('Sending Docker file to ansible server') {
            steps {
                sshagent(['ansible_server']) {
                    sh 'ssh -o StrictHostKeyChecking=no ubuntu@100.25.45.86'
                    sh 'scp /var/lib/jenkins/workspace/health_insurance_cross_sell_prediction/* ubuntu@100.25.45.86:/home/ubuntu/'
                }
            }
        }
    }
}